[tasks.watch]
workspace = false
command = "cargo"
watch = true
args = ["run"]

[cargo-clippy]
clear = true
workspace = false
install_crate = "cargo-clippy"
toolchain = "nightly"
command = "cargo"
args = ["clippy", "-Z", "unstable-options"]

[tasks.clippy-stable]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.clippy-pedantic]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy", "--all", "--", "-D", "clippy::pedantic", "-D", "clippy::nursery", "-D", "warnings"]
